twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        oauthGoogleId: '%env(OAUTH_GOOGLE_ID)%'

when@test:
    twig:
        strict_variables: true
