twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        oauthGoogleId: '%env(OAUTH_GOOGLE_ID)%'

when@test:
    twig:
        strict_variables: true
